/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardRouteImport } from './routes/card'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyMemberNoRouteImport } from './routes/verify/$memberNo'
import { Route as AdminMembersIdRouteImport } from './routes/admin/members/$id'
import { Route as AdminMembersIdCardRouteImport } from './routes/admin/members/$id/card'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMemberNoRoute = VerifyMemberNoRouteImport.update({
  id: '/verify/$memberNo',
  path: '/verify/$memberNo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersIdCardRoute = AdminMembersIdCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AdminMembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/signup'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/admin/members/$id/card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/signup'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/admin/members/$id/card'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/signup'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/admin/members/$id/card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CardRoute: typeof CardRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  VerifyMemberNoRoute: typeof VerifyMemberNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$memberNo': {
      id: '/verify/$memberNo'
      path: '/verify/$memberNo'
      fullPath: '/verify/$memberNo'
      preLoaderRoute: typeof VerifyMemberNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members/$id/card': {
      id: '/admin/members/$id/card'
      path: '/card'
      fullPath: '/admin/members/$id/card'
      preLoaderRoute: typeof AdminMembersIdCardRouteImport
      parentRoute: typeof AdminMembersIdRoute
    }
  }
}

interface AdminMembersIdRouteChildren {
  AdminMembersIdCardRoute: typeof AdminMembersIdCardRoute
}

const AdminMembersIdRouteChildren: AdminMembersIdRouteChildren = {
  AdminMembersIdCardRoute: AdminMembersIdCardRoute,
}

const AdminMembersIdRouteWithChildren = AdminMembersIdRoute._addFileChildren(
  AdminMembersIdRouteChildren,
)

interface AdminRouteChildren {
  AdminMembersIdRoute: typeof AdminMembersIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersIdRoute: AdminMembersIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CardRoute: CardRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  VerifyMemberNoRoute: VerifyMemberNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
