-- PTI Phase 8 — Production Hardening
-- Release security/RLS audit support, finance integrity controls, authenticated
-- rate limiting, production monitoring, export auditing and release-readiness RPCs.

begin;

-- -----------------------------------------------------------------------------
-- Persistent private rate-limit buckets and audited export ledger
-- -----------------------------------------------------------------------------

create table app_private.rate_limit_buckets (
  bucket_key text primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  window_started_at timestamptz not null,
  window_seconds integer not null,
  hit_count integer not null default 1,
  updated_at timestamptz not null default now(),
  constraint rate_limit_action_check check (length(action) between 2 and 80),
  constraint rate_limit_window_check check (window_seconds between 10 and 86400),
  constraint rate_limit_hit_count_check check (hit_count > 0)
);

create index rate_limit_buckets_actor_idx
  on app_private.rate_limit_buckets(actor_id, updated_at desc);
create index rate_limit_buckets_updated_idx
  on app_private.rate_limit_buckets(updated_at);

create table public.production_export_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  export_kind text not null,
  org_unit_id uuid references public.organization_units(id) on delete restrict,
  row_count integer not null,
  filters jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint production_export_kind_check check (export_kind in ('audit_events','finance_ledger')),
  constraint production_export_row_count_check check (row_count >= 0),
  constraint production_export_filters_check check (jsonb_typeof(filters) = 'object')
);

create index production_export_audit_created_idx
  on public.production_export_audit(created_at desc);
create index production_export_audit_actor_idx
  on public.production_export_audit(actor_id, created_at desc);
create index production_export_audit_scope_idx
  on public.production_export_audit(org_unit_id, created_at desc);

alter table public.production_export_audit enable row level security;
revoke all on public.production_export_audit from public, anon, authenticated;
revoke all on app_private.rate_limit_buckets from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- Production access and rate limiting helpers
-- -----------------------------------------------------------------------------

create or replace function app_private.can_manage_production(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_user_id is not null and (
    app_private.is_legacy_admin(p_user_id)
    or exists (
      select 1
      from public.organization_role_assignments ra
      join public.organization_units ou on ou.id = ra.org_unit_id
      where ra.user_id = p_user_id
        and ra.is_active
        and ou.level = 'central'::public.organization_level
        and ra.role = 'super_admin'::public.organization_role
    )
  );
$$;

create or replace function app_private.can_run_production_checks(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_user_id is not null and (
    app_private.is_legacy_admin(p_user_id)
    or exists (
      select 1
      from public.organization_role_assignments ra
      join public.organization_units ou on ou.id = ra.org_unit_id
      where ra.user_id = p_user_id
        and ra.is_active
        and ou.level = 'central'::public.organization_level
        and ra.role = 'super_admin'::public.organization_role
    )
  );
$$;

create or replace function app_private.consume_rate_limit(
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  clean_action text := lower(trim(coalesce(p_action,'')));
  now_value timestamptz := clock_timestamp();
  window_start timestamptz;
  bucket text;
  hits integer;
begin
  if actor is null then raise exception 'Authentication required'; end if;
  if length(clean_action) not between 2 and 80 then raise exception 'Invalid rate-limit action'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 10000 then raise exception 'Invalid rate-limit threshold'; end if;
  if p_window_seconds is null or p_window_seconds < 10 or p_window_seconds > 86400 then raise exception 'Invalid rate-limit window'; end if;

  window_start := to_timestamp((
    floor(extract(epoch from now_value) / p_window_seconds) * p_window_seconds
  )::double precision);
  bucket := actor::text || ':' || clean_action || ':' || extract(epoch from window_start)::bigint::text;

  insert into app_private.rate_limit_buckets(
    bucket_key, actor_id, action, window_started_at, window_seconds, hit_count, updated_at
  )
  values(bucket, actor, clean_action, window_start, p_window_seconds, 1, now_value)
  on conflict (bucket_key) do update
    set hit_count = app_private.rate_limit_buckets.hit_count + 1,
        updated_at = excluded.updated_at
  returning hit_count into hits;

  if hits > p_limit then
    raise exception 'Rate limit exceeded for %; retry after the current window', clean_action
      using errcode = 'P0001';
  end if;

  -- Opportunistic cleanup. This never needs to be exact; old buckets are not used.
  delete from app_private.rate_limit_buckets
  where updated_at < now_value - interval '2 days';

  return greatest(p_limit - hits, 0);
end;
$$;

revoke all on function app_private.can_manage_production(uuid) from public, anon, authenticated;
revoke all on function app_private.can_run_production_checks(uuid) from public, anon, authenticated;
revoke all on function app_private.consume_rate_limit(text,integer,integer) from public, anon, authenticated;
grant execute on function app_private.can_manage_production(uuid) to authenticated;
grant execute on function app_private.can_run_production_checks(uuid) to authenticated;
grant execute on function app_private.consume_rate_limit(text,integer,integer) to authenticated;

-- -----------------------------------------------------------------------------
-- Production monitoring and export implementations
-- -----------------------------------------------------------------------------

create or replace function app_private.my_production_readiness_access_impl()
returns table(
  can_view boolean,
  can_run_checks boolean,
  can_export_audit boolean,
  can_export_finance boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    app_private.can_manage_production(auth.uid()),
    app_private.can_run_production_checks(auth.uid()),
    app_private.can_manage_production(auth.uid()),
    app_private.can_manage_production(auth.uid());
$$;

create or replace function app_private.production_health_summary_impl()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  rls_missing integer := 0;
  direct_write_exposure integer := 0;
  negative_finance integer := 0;
  stale_finance integer := 0;
  unmapped_members integer := 0;
  critical_unread integer := 0;
  legacy_public_definers integer := 0;
  recent_exports integer := 0;
  active_rate_buckets integer := 0;
  overall text;
begin
  if actor is null or not app_private.can_manage_production(actor) then
    raise exception 'Production readiness access required';
  end if;

  select count(*)::integer into rls_missing
  from (
    values
      ('audit_events'),
      ('organization_role_assignments'),
      ('finance_role_assignments'),
      ('fundraising_campaigns'),
      ('donations'),
      ('donation_verification_events'),
      ('donation_reconciliation_events'),
      ('donation_adjustments'),
      ('donation_receipts'),
      ('notification_messages'),
      ('notification_deliveries'),
      ('production_export_audit')
  ) as expected(table_name)
  left join (
    select c.relname, c.relrowsecurity
    from pg_catalog.pg_class c
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
  ) c on c.relname = expected.table_name
  where c.relname is null or not c.relrowsecurity;

  select count(*)::integer into direct_write_exposure
  from (
    values
      ('public.audit_events'),
      ('public.organization_role_assignments'),
      ('public.finance_role_assignments'),
      ('public.donations'),
      ('public.donation_verification_events'),
      ('public.donation_reconciliation_events'),
      ('public.donation_adjustments'),
      ('public.donation_receipts'),
      ('public.notification_messages'),
      ('public.notification_deliveries'),
      ('public.production_export_audit')
  ) as expected(table_name)
  where
    pg_catalog.has_table_privilege('anon', expected.table_name, 'INSERT')
    or pg_catalog.has_table_privilege('anon', expected.table_name, 'UPDATE')
    or pg_catalog.has_table_privilege('anon', expected.table_name, 'DELETE')
    or pg_catalog.has_table_privilege('authenticated', expected.table_name, 'INSERT')
    or pg_catalog.has_table_privilege('authenticated', expected.table_name, 'UPDATE')
    or pg_catalog.has_table_privilege('authenticated', expected.table_name, 'DELETE');

  select count(*)::integer into negative_finance
  from public.donations d
  where d.amount + coalesce((
    select sum(a.amount_delta) from public.donation_adjustments a where a.donation_id = d.id
  ),0) < 0;

  select count(*)::integer into stale_finance
  from public.donations d
  where d.received_at < now() - interval '7 days'
    and app_private.latest_donation_verification_state(d.id) = 'pending'::public.donation_verification_state;

  select count(*)::integer into unmapped_members
  from public.members m
  where m.is_active and m.org_unit_id is null;

  select count(*)::integer into critical_unread
  from public.notification_deliveries d
  join public.notification_messages m on m.id = d.message_id
  where d.read_at is null
    and d.archived_at is null
    and m.status = 'published'::public.notification_status
    and m.severity = 'critical'::public.notification_severity
    and (m.expires_at is null or m.expires_at > now());

  select count(*)::integer into legacy_public_definers
  from pg_catalog.pg_proc p
  join pg_catalog.pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.prosecdef
    and pg_catalog.has_function_privilege('authenticated', p.oid, 'EXECUTE');

  select count(*)::integer into recent_exports
  from public.production_export_audit
  where created_at >= now() - interval '24 hours';

  select count(*)::integer into active_rate_buckets
  from app_private.rate_limit_buckets
  where updated_at >= now() - interval '15 minutes';

  overall := case
    when rls_missing > 0 or direct_write_exposure > 0 or negative_finance > 0 then 'fail'
    when stale_finance > 0 or unmapped_members > 0 or legacy_public_definers > 0 then 'warn'
    else 'ok'
  end;

  return jsonb_build_object(
    'status', overall,
    'database_time', now(),
    'checks', jsonb_build_object(
      'rls_missing', rls_missing,
      'direct_write_exposure', direct_write_exposure,
      'negative_finance_ledger', negative_finance,
      'stale_pending_finance', stale_finance,
      'unmapped_active_members', unmapped_members,
      'critical_unread_deliveries', critical_unread,
      'legacy_public_security_definer_rpcs', legacy_public_definers,
      'exports_last_24h', recent_exports,
      'active_rate_limit_buckets', active_rate_buckets
    )
  );
end;
$$;

create or replace function app_private.production_export_audit_events_impl(
  p_org_unit_id uuid default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit integer default 1000
)
returns table(
  event_id bigint,
  actor_id uuid,
  action text,
  entity_type text,
  entity_id uuid,
  org_unit_id uuid,
  org_unit_name text,
  detail jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  safe_limit integer := greatest(1, least(coalesce(p_limit,1000),5000));
  exported integer := 0;
  export_id bigint;
begin
  if actor is null or not app_private.can_manage_production(actor) then
    raise exception 'Production export access required';
  end if;
  if p_from is not null and p_to is not null and p_to < p_from then
    raise exception 'Invalid export date range';
  end if;
  if p_org_unit_id is not null and not app_private.can_access_org_unit(actor,p_org_unit_id) then
    raise exception 'Organization scope access required';
  end if;
  perform app_private.consume_rate_limit('production_export_audit',10,300);

  return query
  select
    a.id,
    a.actor_id,
    a.action,
    a.entity_type,
    a.entity_id,
    a.org_unit_id,
    ou.name,
    a.detail,
    a.created_at
  from public.audit_events a
  left join public.organization_units ou on ou.id = a.org_unit_id
  where (p_from is null or a.created_at >= p_from)
    and (p_to is null or a.created_at <= p_to)
    and (
      p_org_unit_id is null
      or a.org_unit_id is null
      or exists (
        select 1
        from public.organization_unit_closure c
        where c.ancestor_id = p_org_unit_id
          and c.descendant_id = a.org_unit_id
      )
    )
  order by a.created_at desc, a.id desc
  limit safe_limit;

  get diagnostics exported = row_count;
  insert into public.production_export_audit(actor_id,export_kind,org_unit_id,row_count,filters)
  values(actor,'audit_events',p_org_unit_id,exported,jsonb_build_object('from',p_from,'to',p_to,'limit',safe_limit))
  returning id into export_id;

  insert into public.audit_events(actor_id,action,entity_type,entity_id,org_unit_id,detail)
  values(actor,'production_export_created','production_export',null,p_org_unit_id,
    jsonb_build_object('export_id',export_id,'export_kind','audit_events','row_count',exported));
end;
$$;

create or replace function app_private.production_export_finance_ledger_impl(
  p_org_unit_id uuid default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit integer default 1000
)
returns table(
  donation_no text,
  campaign_no text,
  campaign_title text,
  org_unit_id uuid,
  org_unit_name text,
  base_amount numeric,
  adjustment_total numeric,
  effective_amount numeric,
  currency text,
  payment_method public.finance_payment_method,
  received_at timestamptz,
  verification_state public.donation_verification_state,
  reconciliation_state public.donation_reconciliation_state,
  latest_receipt_no text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  safe_limit integer := greatest(1, least(coalesce(p_limit,1000),5000));
  exported integer := 0;
  export_id bigint;
begin
  if actor is null or not app_private.can_manage_production(actor) then
    raise exception 'Production finance export access required';
  end if;
  if p_from is not null and p_to is not null and p_to < p_from then
    raise exception 'Invalid export date range';
  end if;
  if p_org_unit_id is not null and not app_private.can_view_finance(actor,p_org_unit_id) then
    raise exception 'Finance scope access required';
  end if;
  perform app_private.consume_rate_limit('production_export_finance',10,300);

  return query
  select
    d.donation_no,
    c.campaign_no,
    c.title,
    d.org_unit_id,
    ou.name,
    d.amount,
    coalesce((select sum(a.amount_delta) from public.donation_adjustments a where a.donation_id=d.id),0),
    app_private.effective_donation_amount(d.id),
    d.currency,
    d.payment_method,
    d.received_at,
    app_private.latest_donation_verification_state(d.id),
    app_private.latest_donation_reconciliation_state(d.id),
    (select r.receipt_no from public.donation_receipts r where r.donation_id=d.id order by r.version desc limit 1),
    d.created_at
  from public.donations d
  left join public.fundraising_campaigns c on c.id = d.campaign_id
  join public.organization_units ou on ou.id = d.org_unit_id
  where (p_from is null or d.received_at >= p_from)
    and (p_to is null or d.received_at <= p_to)
    and (
      p_org_unit_id is null
      or exists (
        select 1
        from public.organization_unit_closure scope_tree
        where scope_tree.ancestor_id = p_org_unit_id
          and scope_tree.descendant_id = d.org_unit_id
      )
    )
  order by d.received_at desc, d.created_at desc
  limit safe_limit;

  get diagnostics exported = row_count;
  insert into public.production_export_audit(actor_id,export_kind,org_unit_id,row_count,filters)
  values(actor,'finance_ledger',p_org_unit_id,exported,jsonb_build_object('from',p_from,'to',p_to,'limit',safe_limit,'pii','excluded'))
  returning id into export_id;

  insert into public.audit_events(actor_id,action,entity_type,entity_id,org_unit_id,detail)
  values(actor,'production_export_created','production_export',null,p_org_unit_id,
    jsonb_build_object('export_id',export_id,'export_kind','finance_ledger','row_count',exported,'pii','excluded'));
end;
$$;

create or replace function app_private.list_production_exports_impl(p_limit integer default 50)
returns table(
  id bigint,
  export_kind text,
  actor_id uuid,
  actor_email text,
  org_unit_id uuid,
  org_unit_name text,
  row_count integer,
  filters jsonb,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  safe_limit integer := greatest(1, least(coalesce(p_limit,50),200));
begin
  if actor is null or not app_private.can_manage_production(actor) then
    raise exception 'Production readiness access required';
  end if;
  return query
  select e.id,e.export_kind,e.actor_id,p.email,e.org_unit_id,ou.name,e.row_count,e.filters,e.created_at
  from public.production_export_audit e
  left join public.profiles p on p.id=e.actor_id
  left join public.organization_units ou on ou.id=e.org_unit_id
  order by e.created_at desc,e.id desc
  limit safe_limit;
end;
$$;

revoke all on function app_private.my_production_readiness_access_impl() from public, anon, authenticated;
revoke all on function app_private.production_health_summary_impl() from public, anon, authenticated;
revoke all on function app_private.production_export_audit_events_impl(uuid,timestamptz,timestamptz,integer) from public, anon, authenticated;
revoke all on function app_private.production_export_finance_ledger_impl(uuid,timestamptz,timestamptz,integer) from public, anon, authenticated;
revoke all on function app_private.list_production_exports_impl(integer) from public, anon, authenticated;

grant execute on function app_private.my_production_readiness_access_impl() to authenticated;
grant execute on function app_private.production_health_summary_impl() to authenticated;
grant execute on function app_private.production_export_audit_events_impl(uuid,timestamptz,timestamptz,integer) to authenticated;
grant execute on function app_private.production_export_finance_ledger_impl(uuid,timestamptz,timestamptz,integer) to authenticated;
grant execute on function app_private.list_production_exports_impl(integer) to authenticated;

-- -----------------------------------------------------------------------------
-- Public SECURITY INVOKER API
-- -----------------------------------------------------------------------------

create or replace function public.my_production_readiness_access()
returns table(
  can_view boolean,
  can_run_checks boolean,
  can_export_audit boolean,
  can_export_finance boolean
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.my_production_readiness_access_impl();
$$;

create or replace function public.production_health_summary()
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select app_private.production_health_summary_impl();
$$;

create or replace function public.production_export_audit_events(
  p_org_unit_id uuid default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit integer default 1000
)
returns table(
  event_id bigint,
  actor_id uuid,
  action text,
  entity_type text,
  entity_id uuid,
  org_unit_id uuid,
  org_unit_name text,
  detail jsonb,
  created_at timestamptz
)
language sql
security invoker
set search_path = ''
as $$
  select * from app_private.production_export_audit_events_impl(p_org_unit_id,p_from,p_to,p_limit);
$$;

create or replace function public.production_export_finance_ledger(
  p_org_unit_id uuid default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit integer default 1000
)
returns table(
  donation_no text,
  campaign_no text,
  campaign_title text,
  org_unit_id uuid,
  org_unit_name text,
  base_amount numeric,
  adjustment_total numeric,
  effective_amount numeric,
  currency text,
  payment_method public.finance_payment_method,
  received_at timestamptz,
  verification_state public.donation_verification_state,
  reconciliation_state public.donation_reconciliation_state,
  latest_receipt_no text,
  created_at timestamptz
)
language sql
security invoker
set search_path = ''
as $$
  select * from app_private.production_export_finance_ledger_impl(p_org_unit_id,p_from,p_to,p_limit);
$$;

create or replace function public.list_production_exports(p_limit integer default 50)
returns table(
  id bigint,
  export_kind text,
  actor_id uuid,
  actor_email text,
  org_unit_id uuid,
  org_unit_name text,
  row_count integer,
  filters jsonb,
  created_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.list_production_exports_impl(p_limit);
$$;

revoke all on function public.my_production_readiness_access() from public, anon, authenticated;
revoke all on function public.production_health_summary() from public, anon, authenticated;
revoke all on function public.production_export_audit_events(uuid,timestamptz,timestamptz,integer) from public, anon, authenticated;
revoke all on function public.production_export_finance_ledger(uuid,timestamptz,timestamptz,integer) from public, anon, authenticated;
revoke all on function public.list_production_exports(integer) from public, anon, authenticated;

grant execute on function public.my_production_readiness_access() to authenticated;
grant execute on function public.production_health_summary() to authenticated;
grant execute on function public.production_export_audit_events(uuid,timestamptz,timestamptz,integer) to authenticated;
grant execute on function public.production_export_finance_ledger(uuid,timestamptz,timestamptz,integer) to authenticated;
grant execute on function public.list_production_exports(integer) to authenticated;

-- -----------------------------------------------------------------------------
-- Rate-limit high-impact finance and command-center mutation RPCs.
-- Public wrappers remain SECURITY INVOKER; private implementations retain all
-- authorization and audit logic.
-- -----------------------------------------------------------------------------

create or replace function public.save_fundraising_campaign(p_campaign_id uuid, p_org_unit_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_campaign_write',60,300);
  return app_private.save_fundraising_campaign_impl(p_campaign_id,p_org_unit_id,p_payload);
end;
$$;

create or replace function public.record_finance_donation(p_campaign_id uuid, p_org_unit_id uuid, p_payload jsonb)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_donation_record',120,300);
  return app_private.record_finance_donation_impl(p_campaign_id,p_org_unit_id,p_payload);
end;
$$;

create or replace function public.set_donation_verification(
  p_donation_id uuid,
  p_state public.donation_verification_state,
  p_note text default null
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_verify',120,300);
  perform app_private.set_donation_verification_impl(p_donation_id,p_state,p_note);
end;
$$;

create or replace function public.set_donation_reconciliation(
  p_donation_id uuid,
  p_state public.donation_reconciliation_state,
  p_reference text default null,
  p_note text default null
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_reconcile',120,300);
  perform app_private.set_donation_reconciliation_impl(p_donation_id,p_state,p_reference,p_note);
end;
$$;

create or replace function public.add_donation_adjustment(
  p_donation_id uuid,
  p_kind public.donation_adjustment_kind,
  p_amount_delta numeric,
  p_reason text,
  p_reference text default null
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_adjustment',60,300);
  return app_private.add_donation_adjustment_impl(p_donation_id,p_kind,p_amount_delta,p_reason,p_reference);
end;
$$;

create or replace function public.issue_donation_receipt(p_donation_id uuid)
returns text
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_receipt',120,300);
  return app_private.issue_donation_receipt_impl(p_donation_id);
end;
$$;

create or replace function public.assign_finance_role_by_email(
  p_email text,
  p_role public.finance_role,
  p_org_unit_id uuid,
  p_note text default null
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_role_assign',20,300);
  return app_private.assign_finance_role_by_email_impl(p_email,p_role,p_org_unit_id,p_note);
end;
$$;

create or replace function public.revoke_finance_role(p_assignment_id uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('finance_role_revoke',20,300);
  perform app_private.revoke_finance_role_impl(p_assignment_id);
end;
$$;

create or replace function public.publish_notification(
  p_org_unit_id uuid,
  p_kind public.notification_kind,
  p_severity public.notification_severity,
  p_title text,
  p_body text,
  p_audience public.notification_audience,
  p_operation_id uuid default null,
  p_action_url text default null,
  p_expires_at timestamptz default null,
  p_target_spec jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('notification_publish',30,300);
  return app_private.publish_notification_impl(
    p_org_unit_id,p_kind,p_severity,p_title,p_body,p_audience,
    p_operation_id,p_action_url,p_expires_at,p_target_spec
  );
end;
$$;

create or replace function public.cancel_notification(p_message_id uuid)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('notification_cancel',30,300);
  perform app_private.cancel_notification_impl(p_message_id);
end;
$$;

create or replace function public.generate_due_duty_reminders(p_horizon_hours integer default 24)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
begin
  perform app_private.consume_rate_limit('duty_reminder_sweep',12,300);
  return app_private.generate_due_duty_reminders_impl(p_horizon_hours);
end;
$$;

-- Re-pin ACLs after CREATE OR REPLACE for clarity.
revoke all on function public.save_fundraising_campaign(uuid,uuid,jsonb) from public, anon;
revoke all on function public.record_finance_donation(uuid,uuid,jsonb) from public, anon;
revoke all on function public.set_donation_verification(uuid,public.donation_verification_state,text) from public, anon;
revoke all on function public.set_donation_reconciliation(uuid,public.donation_reconciliation_state,text,text) from public, anon;
revoke all on function public.add_donation_adjustment(uuid,public.donation_adjustment_kind,numeric,text,text) from public, anon;
revoke all on function public.issue_donation_receipt(uuid) from public, anon;
revoke all on function public.assign_finance_role_by_email(text,public.finance_role,uuid,text) from public, anon;
revoke all on function public.revoke_finance_role(uuid) from public, anon;
revoke all on function public.publish_notification(uuid,public.notification_kind,public.notification_severity,text,text,public.notification_audience,uuid,text,timestamptz,jsonb) from public, anon;
revoke all on function public.cancel_notification(uuid) from public, anon;
revoke all on function public.generate_due_duty_reminders(integer) from public, anon;

grant execute on function public.save_fundraising_campaign(uuid,uuid,jsonb) to authenticated;
grant execute on function public.record_finance_donation(uuid,uuid,jsonb) to authenticated;
grant execute on function public.set_donation_verification(uuid,public.donation_verification_state,text) to authenticated;
grant execute on function public.set_donation_reconciliation(uuid,public.donation_reconciliation_state,text,text) to authenticated;
grant execute on function public.add_donation_adjustment(uuid,public.donation_adjustment_kind,numeric,text,text) to authenticated;
grant execute on function public.issue_donation_receipt(uuid) to authenticated;
grant execute on function public.assign_finance_role_by_email(text,public.finance_role,uuid,text) to authenticated;
grant execute on function public.revoke_finance_role(uuid) to authenticated;
grant execute on function public.publish_notification(uuid,public.notification_kind,public.notification_severity,text,text,public.notification_audience,uuid,text,timestamptz,jsonb) to authenticated;
grant execute on function public.cancel_notification(uuid) to authenticated;
grant execute on function public.generate_due_duty_reminders(integer) to authenticated;

insert into public.audit_events(actor_id,action,entity_type,entity_id,org_unit_id,detail)
values(null,'production_hardening_installed','system_release',null,null,
  jsonb_build_object(
    'phase','8',
    'rate_limiting',true,
    'production_exports',true,
    'production_health',true,
    'installed_at',now()
  ));

commit;
