-- PTI Digital Operations Platform — Phase 7
-- Notifications & Operational Command Center
-- Targeted announcements, alerts, duty reminders and operational updates.
-- Depends on Phase 1–6 migrations.

begin;

-- -----------------------------------------------------------------------------
-- Types
-- -----------------------------------------------------------------------------

create type public.notification_kind as enum (
  'announcement',
  'alert',
  'duty_reminder',
  'operation_update'
);

create type public.notification_severity as enum (
  'info',
  'success',
  'warning',
  'critical'
);

create type public.notification_audience as enum (
  'org_scope',
  'members',
  'volunteers',
  'organization_roles',
  'finance_roles',
  'operation_participants',
  'specific_users'
);

create type public.notification_status as enum (
  'published',
  'cancelled'
);

-- -----------------------------------------------------------------------------
-- Core notification ledger
-- -----------------------------------------------------------------------------

create table public.notification_messages (
  id uuid primary key default gen_random_uuid(),
  notification_no text not null unique,
  kind public.notification_kind not null,
  severity public.notification_severity not null default 'info',
  status public.notification_status not null default 'published',
  title text not null,
  body text not null,
  audience public.notification_audience not null,
  org_unit_id uuid not null references public.organization_units(id) on delete restrict,
  operation_id uuid references public.operations(id) on delete set null,
  target_spec jsonb not null default '{}'::jsonb,
  action_url text,
  source_key text unique,
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  cancelled_at timestamptz,
  cancelled_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint notification_messages_title_check check (length(trim(title)) between 2 and 160),
  constraint notification_messages_body_check check (length(trim(body)) between 2 and 4000),
  constraint notification_messages_action_url_check check (
    action_url is null
    or (
      length(action_url) <= 500
      and (action_url like '/%' or action_url like 'https://%')
    )
  ),
  constraint notification_messages_target_spec_check check (jsonb_typeof(target_spec) = 'object'),
  constraint notification_messages_expiry_check check (expires_at is null or expires_at > published_at),
  constraint notification_messages_cancel_state_check check (
    (status = 'published'::public.notification_status and cancelled_at is null and cancelled_by is null)
    or (status = 'cancelled'::public.notification_status and cancelled_at is not null)
  )
);

create table public.notification_deliveries (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.notification_messages(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  delivered_at timestamptz not null default now(),
  read_at timestamptz,
  archived_at timestamptz,
  unique (message_id, recipient_user_id),
  constraint notification_deliveries_archive_check check (archived_at is null or archived_at >= delivered_at),
  constraint notification_deliveries_read_check check (read_at is null or read_at >= delivered_at)
);

create index notification_messages_scope_idx
  on public.notification_messages(org_unit_id, published_at desc);
create index notification_messages_operation_idx
  on public.notification_messages(operation_id, published_at desc)
  where operation_id is not null;
create index notification_messages_active_idx
  on public.notification_messages(status, published_at desc, expires_at);
create index notification_messages_created_by_idx
  on public.notification_messages(created_by)
  where created_by is not null;
create index notification_messages_cancelled_by_idx
  on public.notification_messages(cancelled_by)
  where cancelled_by is not null;
create index notification_deliveries_recipient_idx
  on public.notification_deliveries(recipient_user_id, archived_at, read_at, delivered_at desc);
create index notification_deliveries_message_idx
  on public.notification_deliveries(message_id, delivered_at desc);

-- -----------------------------------------------------------------------------
-- Authorization helpers
-- -----------------------------------------------------------------------------

create or replace function app_private.can_view_command_center(
  p_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    app_private.is_legacy_admin(p_user_id)
    or exists (
      select 1
      from public.organization_role_assignments ra
      where ra.user_id = p_user_id
        and ra.is_active
        and ra.role in (
          'super_admin'::public.organization_role,
          'central_leadership'::public.organization_role,
          'national_operations_admin'::public.organization_role,
          'national_finance_admin'::public.organization_role,
          'provincial_coordinator'::public.organization_role,
          'divisional_coordinator'::public.organization_role,
          'district_coordinator'::public.organization_role,
          'tehsil_coordinator'::public.organization_role,
          'supervisor'::public.organization_role,
          'auditor'::public.organization_role
        )
    )
    or exists (
      select 1
      from public.operation_coordinators oc
      where oc.user_id = p_user_id
        and oc.is_active
    );
$$;

create or replace function app_private.can_manage_notifications(
  p_user_id uuid,
  p_target_org_unit uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    app_private.is_legacy_admin(p_user_id)
    or exists (
      select 1
      from public.organization_role_assignments ra
      join public.organization_units scope_unit on scope_unit.id = ra.org_unit_id
      where ra.user_id = p_user_id
        and ra.is_active
        and scope_unit.is_active
        and ra.role in (
          'super_admin'::public.organization_role,
          'central_leadership'::public.organization_role,
          'national_operations_admin'::public.organization_role,
          'provincial_coordinator'::public.organization_role,
          'divisional_coordinator'::public.organization_role,
          'district_coordinator'::public.organization_role,
          'tehsil_coordinator'::public.organization_role,
          'supervisor'::public.organization_role
        )
        and app_private.is_org_descendant(p_target_org_unit, ra.org_unit_id)
    );
$$;

create or replace function app_private.user_in_notification_scope(
  p_user_id uuid,
  p_org_unit_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.members m
    where m.user_id = p_user_id
      and m.is_active
      and m.org_unit_id is not null
      and app_private.is_org_descendant(m.org_unit_id, p_org_unit_id)
  )
  or exists (
    select 1
    from public.volunteer_profiles vp
    where vp.user_id = p_user_id
      and vp.is_active
      and app_private.is_org_descendant(vp.org_unit_id, p_org_unit_id)
  )
  or exists (
    select 1
    from public.organization_role_assignments ra
    where ra.user_id = p_user_id
      and ra.is_active
      and app_private.is_org_descendant(ra.org_unit_id, p_org_unit_id)
  )
  or exists (
    select 1
    from public.finance_role_assignments fra
    where fra.user_id = p_user_id
      and fra.is_active
      and app_private.is_org_descendant(fra.org_unit_id, p_org_unit_id)
  );
$$;

revoke all on function app_private.can_view_command_center(uuid) from public, anon, authenticated;
revoke all on function app_private.can_manage_notifications(uuid,uuid) from public, anon, authenticated;
revoke all on function app_private.user_in_notification_scope(uuid,uuid) from public, anon, authenticated;

-- RLS policies evaluate these helpers as authenticated users.
grant execute on function app_private.can_view_command_center(uuid) to authenticated;
grant execute on function app_private.can_manage_notifications(uuid,uuid) to authenticated;
grant execute on function app_private.user_in_notification_scope(uuid,uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- Recipient resolver
-- -----------------------------------------------------------------------------

create or replace function app_private.notification_recipient_ids(
  p_audience public.notification_audience,
  p_org_unit_id uuid,
  p_operation_id uuid,
  p_target_spec jsonb
)
returns table(user_id uuid)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_org_unit_id is null then
    raise exception 'Notification scope is required';
  end if;

  if p_audience = 'org_scope'::public.notification_audience then
    return query
    select distinct recipients.user_id
    from (
      select m.user_id
      from public.members m
      where m.is_active
        and m.org_unit_id is not null
        and app_private.is_org_descendant(m.org_unit_id, p_org_unit_id)

      union

      select vp.user_id
      from public.volunteer_profiles vp
      where vp.is_active
        and app_private.is_org_descendant(vp.org_unit_id, p_org_unit_id)

      union

      select ra.user_id
      from public.organization_role_assignments ra
      where ra.is_active
        and app_private.is_org_descendant(ra.org_unit_id, p_org_unit_id)

      union

      select fra.user_id
      from public.finance_role_assignments fra
      where fra.is_active
        and app_private.is_org_descendant(fra.org_unit_id, p_org_unit_id)
    ) recipients;
    return;
  end if;

  if p_audience = 'members'::public.notification_audience then
    return query
    select distinct m.user_id
    from public.members m
    where m.is_active
      and m.org_unit_id is not null
      and app_private.is_org_descendant(m.org_unit_id, p_org_unit_id);
    return;
  end if;

  if p_audience = 'volunteers'::public.notification_audience then
    return query
    select distinct vp.user_id
    from public.volunteer_profiles vp
    where vp.is_active
      and app_private.is_org_descendant(vp.org_unit_id, p_org_unit_id);
    return;
  end if;

  if p_audience = 'organization_roles'::public.notification_audience then
    return query
    select distinct ra.user_id
    from public.organization_role_assignments ra
    where ra.is_active
      and app_private.is_org_descendant(ra.org_unit_id, p_org_unit_id)
      and ra.role = any (
        coalesce(
          array(
            select value::public.organization_role
            from jsonb_array_elements_text(coalesce(p_target_spec->'organization_roles', '[]'::jsonb)) as value
          ),
          '{}'::public.organization_role[]
        )
      );
    return;
  end if;

  if p_audience = 'finance_roles'::public.notification_audience then
    return query
    select distinct fra.user_id
    from public.finance_role_assignments fra
    where fra.is_active
      and app_private.is_org_descendant(fra.org_unit_id, p_org_unit_id)
      and fra.role = any (
        coalesce(
          array(
            select value::public.finance_role
            from jsonb_array_elements_text(coalesce(p_target_spec->'finance_roles', '[]'::jsonb)) as value
          ),
          '{}'::public.finance_role[]
        )
      );
    return;
  end if;

  if p_audience = 'operation_participants'::public.notification_audience then
    if p_operation_id is null then
      raise exception 'Operation participant notifications require an operation';
    end if;

    return query
    select distinct recipients.user_id
    from (
      select oc.user_id
      from public.operation_coordinators oc
      where oc.operation_id = p_operation_id and oc.is_active

      union

      select vp.user_id
      from public.operation_team_members otm
      join public.operation_teams ot on ot.id = otm.team_id
      join public.volunteer_profiles vp on vp.id = otm.volunteer_id
      where ot.operation_id = p_operation_id
        and otm.is_active
        and vp.is_active

      union

      select vp.user_id
      from public.duty_assignments da
      join public.operation_duties od on od.id = da.duty_id
      join public.volunteer_profiles vp on vp.id = da.volunteer_id
      where od.operation_id = p_operation_id
        and da.status <> 'cancelled'::public.duty_status
        and vp.is_active
    ) recipients;
    return;
  end if;

  if p_audience = 'specific_users'::public.notification_audience then
    return query
    select distinct selected.user_id
    from (
      select value::uuid as user_id
      from jsonb_array_elements_text(coalesce(p_target_spec->'user_ids', '[]'::jsonb)) as value
    ) selected
    where app_private.user_in_notification_scope(selected.user_id, p_org_unit_id);
    return;
  end if;

  raise exception 'Unsupported notification audience';
end;
$$;

revoke all on function app_private.notification_recipient_ids(public.notification_audience,uuid,uuid,jsonb) from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- Access + inbox implementations
-- -----------------------------------------------------------------------------

create or replace function app_private.my_command_center_access_impl()
returns table(
  can_view boolean,
  can_manage boolean,
  default_org_unit_id uuid,
  default_org_unit_name text,
  default_org_unit_level public.organization_level
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  default_scope public.organization_units;
begin
  if actor is null then
    return query select false, false, null::uuid, null::text, null::public.organization_level;
    return;
  end if;

  if app_private.is_legacy_admin(actor) then
    select * into default_scope
    from public.organization_units ou
    where ou.level = 'central'::public.organization_level
      and ou.is_active
    order by ou.created_at
    limit 1;
  else
    select ou.* into default_scope
    from public.organization_role_assignments ra
    join public.organization_units ou on ou.id = ra.org_unit_id
    where ra.user_id = actor
      and ra.is_active
      and ou.is_active
      and ra.role in (
        'super_admin'::public.organization_role,
        'central_leadership'::public.organization_role,
        'national_operations_admin'::public.organization_role,
        'national_finance_admin'::public.organization_role,
        'provincial_coordinator'::public.organization_role,
        'divisional_coordinator'::public.organization_role,
        'district_coordinator'::public.organization_role,
        'tehsil_coordinator'::public.organization_role,
        'supervisor'::public.organization_role,
        'auditor'::public.organization_role
      )
    order by case ou.level
      when 'central'::public.organization_level then 0
      when 'province'::public.organization_level then 1
      when 'division'::public.organization_level then 2
      when 'district'::public.organization_level then 3
      when 'tehsil'::public.organization_level then 4
      else 9 end,
      ou.name
    limit 1;

    if default_scope.id is null then
      select ou.* into default_scope
      from public.operation_coordinators oc
      join public.operations o on o.id = oc.operation_id
      join public.organization_units ou on ou.id = o.org_unit_id
      where oc.user_id = actor
        and oc.is_active
        and ou.is_active
      order by o.created_at desc
      limit 1;
    end if;
  end if;

  return query
  select
    app_private.can_view_command_center(actor),
    (
      app_private.is_legacy_admin(actor)
      or exists (
        select 1
        from public.organization_role_assignments ra
        where ra.user_id = actor
          and ra.is_active
          and ra.role in (
            'super_admin'::public.organization_role,
            'central_leadership'::public.organization_role,
            'national_operations_admin'::public.organization_role,
            'provincial_coordinator'::public.organization_role,
            'divisional_coordinator'::public.organization_role,
            'district_coordinator'::public.organization_role,
            'tehsil_coordinator'::public.organization_role,
            'supervisor'::public.organization_role
          )
      )
      or exists (
        select 1 from public.operation_coordinators oc
        where oc.user_id = actor and oc.is_active
      )
    ),
    default_scope.id,
    default_scope.name,
    default_scope.level;
end;
$$;

create or replace function app_private.list_notification_scopes_impl()
returns table(
  id uuid,
  parent_id uuid,
  level public.organization_level,
  name text,
  code text
)
language sql
stable
security definer
set search_path = ''
as $$
  select ou.id, ou.parent_id, ou.level, ou.name, ou.code
  from public.organization_units ou
  where ou.is_active
    and (
      app_private.can_access_org_unit(auth.uid(), ou.id)
      or exists (
        select 1
        from public.operation_coordinators oc
        join public.operations o on o.id = oc.operation_id
        where oc.user_id = auth.uid()
          and oc.is_active
          and o.org_unit_id = ou.id
      )
    )
  order by
    case ou.level
      when 'central'::public.organization_level then 0
      when 'province'::public.organization_level then 1
      when 'division'::public.organization_level then 2
      when 'district'::public.organization_level then 3
      when 'tehsil'::public.organization_level then 4
      else 9 end,
    ou.name;
$$;

create or replace function app_private.list_notification_operations_impl(
  p_org_unit_id uuid default null
)
returns table(
  id uuid,
  org_unit_id uuid,
  org_unit_name text,
  title text,
  status public.operation_status,
  starts_at timestamptz,
  ends_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select o.id, o.org_unit_id, ou.name, o.title, o.status, o.starts_at, o.ends_at
  from public.operations o
  join public.organization_units ou on ou.id = o.org_unit_id
  where app_private.can_manage_operation(auth.uid(), o.id)
    and (
      p_org_unit_id is null
      or app_private.is_org_descendant(o.org_unit_id, p_org_unit_id)
    )
  order by coalesce(o.starts_at, o.created_at) desc, o.title;
$$;

create or replace function app_private.my_notification_unread_count_impl()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select count(*)::bigint
  from public.notification_deliveries d
  join public.notification_messages m on m.id = d.message_id
  where d.recipient_user_id = auth.uid()
    and d.read_at is null
    and d.archived_at is null
    and m.status = 'published'::public.notification_status
    and m.published_at <= now()
    and (m.expires_at is null or m.expires_at > now());
$$;

create or replace function app_private.list_my_notifications_impl(
  p_limit integer default 50,
  p_before timestamptz default null
)
returns table(
  delivery_id bigint,
  message_id uuid,
  notification_no text,
  kind public.notification_kind,
  severity public.notification_severity,
  title text,
  body text,
  action_url text,
  operation_id uuid,
  org_unit_id uuid,
  org_unit_name text,
  published_at timestamptz,
  expires_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  archived_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  safe_limit integer := greatest(1, least(coalesce(p_limit, 50), 100));
begin
  return query
  select
    d.id,
    m.id,
    m.notification_no,
    m.kind,
    m.severity,
    m.title,
    m.body,
    m.action_url,
    m.operation_id,
    m.org_unit_id,
    ou.name,
    m.published_at,
    m.expires_at,
    d.delivered_at,
    d.read_at,
    d.archived_at
  from public.notification_deliveries d
  join public.notification_messages m on m.id = d.message_id
  join public.organization_units ou on ou.id = m.org_unit_id
  where d.recipient_user_id = auth.uid()
    and d.archived_at is null
    and m.status = 'published'::public.notification_status
    and m.published_at <= now()
    and (m.expires_at is null or m.expires_at > now())
    and (p_before is null or d.delivered_at < p_before)
  order by d.delivered_at desc, d.id desc
  limit safe_limit;
end;
$$;

create or replace function app_private.mark_my_notification_read_impl(
  p_delivery_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.notification_deliveries d
  set read_at = coalesce(d.read_at, now())
  where d.id = p_delivery_id
    and d.recipient_user_id = auth.uid();

  if not found then
    raise exception 'Notification delivery not found';
  end if;
end;
$$;

create or replace function app_private.mark_all_my_notifications_read_impl()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected integer;
begin
  update public.notification_deliveries d
  set read_at = coalesce(d.read_at, now())
  from public.notification_messages m
  where m.id = d.message_id
    and d.recipient_user_id = auth.uid()
    and d.read_at is null
    and d.archived_at is null
    and m.status = 'published'::public.notification_status
    and m.published_at <= now()
    and (m.expires_at is null or m.expires_at > now());

  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace function app_private.archive_my_notification_impl(
  p_delivery_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.notification_deliveries d
  set archived_at = coalesce(d.archived_at, now()),
      read_at = coalesce(d.read_at, now())
  where d.id = p_delivery_id
    and d.recipient_user_id = auth.uid();

  if not found then
    raise exception 'Notification delivery not found';
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- Command center implementations
-- -----------------------------------------------------------------------------

create or replace function app_private.list_command_center_messages_impl(
  p_org_unit_id uuid default null,
  p_limit integer default 50
)
returns table(
  id uuid,
  notification_no text,
  kind public.notification_kind,
  severity public.notification_severity,
  status public.notification_status,
  title text,
  body text,
  audience public.notification_audience,
  org_unit_id uuid,
  org_unit_name text,
  operation_id uuid,
  operation_title text,
  action_url text,
  published_at timestamptz,
  expires_at timestamptz,
  created_by uuid,
  recipient_count bigint,
  read_count bigint,
  unread_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  safe_limit integer := greatest(1, least(coalesce(p_limit, 50), 100));
begin
  if actor is null or not app_private.can_view_command_center(actor) then
    raise exception 'Command center access required';
  end if;

  return query
  select
    m.id,
    m.notification_no,
    m.kind,
    m.severity,
    m.status,
    m.title,
    m.body,
    m.audience,
    m.org_unit_id,
    ou.name,
    m.operation_id,
    o.title,
    m.action_url,
    m.published_at,
    m.expires_at,
    m.created_by,
    count(d.id)::bigint,
    count(d.id) filter (where d.read_at is not null)::bigint,
    count(d.id) filter (where d.read_at is null and d.archived_at is null)::bigint
  from public.notification_messages m
  join public.organization_units ou on ou.id = m.org_unit_id
  left join public.operations o on o.id = m.operation_id
  left join public.notification_deliveries d on d.message_id = m.id
  where (
      app_private.can_manage_notifications(actor, m.org_unit_id)
      or (m.operation_id is not null and app_private.can_manage_operation(actor, m.operation_id))
      or app_private.can_access_org_unit(actor, m.org_unit_id)
    )
    and (
      p_org_unit_id is null
      or app_private.is_org_descendant(m.org_unit_id, p_org_unit_id)
    )
  group by m.id, ou.name, o.title
  order by m.published_at desc
  limit safe_limit;
end;
$$;

create or replace function app_private.publish_notification_impl(
  p_org_unit_id uuid,
  p_kind public.notification_kind,
  p_severity public.notification_severity,
  p_title text,
  p_body text,
  p_audience public.notification_audience,
  p_operation_id uuid default null,
  p_action_url text default null,
  p_expires_at timestamptz default null,
  p_target_spec jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  clean_title text := trim(coalesce(p_title, ''));
  clean_body text := trim(coalesce(p_body, ''));
  clean_action text := nullif(trim(coalesce(p_action_url, '')), '');
  next_id uuid := gen_random_uuid();
  next_no text := 'PTI-NOT-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(replace(next_id::text, '-', ''), 1, 8));
  recipient_total integer := 0;
  operation_row public.operations;
begin
  if actor is null then raise exception 'Authentication required'; end if;
  if p_org_unit_id is null then raise exception 'Organization scope is required'; end if;
  if length(clean_title) < 2 or length(clean_title) > 160 then raise exception 'Notification title must be 2–160 characters'; end if;
  if length(clean_body) < 2 or length(clean_body) > 4000 then raise exception 'Notification body must be 2–4000 characters'; end if;
  if p_expires_at is not null and p_expires_at <= now() then raise exception 'Expiry must be in the future'; end if;
  if clean_action is not null and clean_action not like '/%' and clean_action not like 'https://%' then raise exception 'Action URL must be a relative path or HTTPS URL'; end if;
  if jsonb_typeof(coalesce(p_target_spec, '{}'::jsonb)) <> 'object' then raise exception 'Target specification must be a JSON object'; end if;

  if p_operation_id is not null then
    select * into operation_row from public.operations where id = p_operation_id;
    if not found then raise exception 'Operation not found'; end if;
    if not app_private.is_org_descendant(operation_row.org_unit_id, p_org_unit_id) then
      raise exception 'Operation is outside the selected notification scope';
    end if;
  end if;

  if p_audience = 'operation_participants'::public.notification_audience
     or p_kind = 'operation_update'::public.notification_kind then
    if p_operation_id is null then raise exception 'Operation notifications require an operation'; end if;
    if not app_private.can_manage_operation(actor, p_operation_id) then raise exception 'Operation notification access required'; end if;
  elsif not app_private.can_manage_notifications(actor, p_org_unit_id) then
    raise exception 'Notification publishing access required';
  end if;

  if p_audience = 'organization_roles'::public.notification_audience
     and jsonb_array_length(coalesce(p_target_spec->'organization_roles', '[]'::jsonb)) = 0 then
    raise exception 'Choose at least one organization role';
  end if;

  if p_audience = 'finance_roles'::public.notification_audience
     and jsonb_array_length(coalesce(p_target_spec->'finance_roles', '[]'::jsonb)) = 0 then
    raise exception 'Choose at least one finance role';
  end if;

  if p_audience = 'specific_users'::public.notification_audience
     and jsonb_array_length(coalesce(p_target_spec->'user_ids', '[]'::jsonb)) = 0 then
    raise exception 'Choose at least one target user';
  end if;

  insert into public.notification_messages(
    id, notification_no, kind, severity, status, title, body, audience,
    org_unit_id, operation_id, target_spec, action_url, published_at,
    expires_at, created_by
  )
  values(
    next_id, next_no, p_kind, p_severity, 'published', clean_title, clean_body,
    p_audience, p_org_unit_id, p_operation_id, coalesce(p_target_spec, '{}'::jsonb),
    clean_action, now(), p_expires_at, actor
  );

  insert into public.notification_deliveries(message_id, recipient_user_id)
  select next_id, recipients.user_id
  from app_private.notification_recipient_ids(
    p_audience,
    p_org_unit_id,
    p_operation_id,
    coalesce(p_target_spec, '{}'::jsonb)
  ) recipients
  on conflict (message_id, recipient_user_id) do nothing;

  get diagnostics recipient_total = row_count;

  if recipient_total = 0 then
    raise exception 'No eligible recipients were found for this notification target';
  end if;

  insert into public.audit_events(actor_id, action, entity_type, entity_id, org_unit_id, detail)
  values(
    actor,
    'notification_published',
    'notification_message',
    next_id,
    p_org_unit_id,
    jsonb_build_object(
      'notification_no', next_no,
      'kind', p_kind,
      'severity', p_severity,
      'audience', p_audience,
      'operation_id', p_operation_id,
      'recipient_count', recipient_total
    )
  );

  return jsonb_build_object(
    'message_id', next_id,
    'notification_no', next_no,
    'recipient_count', recipient_total
  );
end;
$$;

create or replace function app_private.cancel_notification_impl(
  p_message_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  row_data public.notification_messages;
begin
  if actor is null then raise exception 'Authentication required'; end if;

  select * into row_data
  from public.notification_messages
  where id = p_message_id
  for update;

  if not found then raise exception 'Notification not found'; end if;

  if not (
    app_private.can_manage_notifications(actor, row_data.org_unit_id)
    or (row_data.operation_id is not null and app_private.can_manage_operation(actor, row_data.operation_id))
  ) then
    raise exception 'Notification cancellation access required';
  end if;

  if row_data.status = 'cancelled'::public.notification_status then return; end if;

  update public.notification_messages
  set status = 'cancelled',
      cancelled_at = now(),
      cancelled_by = actor
  where id = row_data.id;

  insert into public.audit_events(actor_id, action, entity_type, entity_id, org_unit_id, detail)
  values(actor, 'notification_cancelled', 'notification_message', row_data.id, row_data.org_unit_id,
    jsonb_build_object('notification_no', row_data.notification_no));
end;
$$;

-- -----------------------------------------------------------------------------
-- Automatic duty assignment + reminder helpers
-- -----------------------------------------------------------------------------

create or replace function app_private.publish_direct_notification_to_user(
  p_user_id uuid,
  p_org_unit_id uuid,
  p_operation_id uuid,
  p_kind public.notification_kind,
  p_severity public.notification_severity,
  p_title text,
  p_body text,
  p_action_url text,
  p_source_key text,
  p_created_by uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_id uuid := gen_random_uuid();
  next_no text := 'PTI-NOT-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(replace(next_id::text, '-', ''), 1, 8));
begin
  insert into public.notification_messages(
    id, notification_no, kind, severity, status, title, body, audience,
    org_unit_id, operation_id, target_spec, action_url, source_key,
    published_at, created_by
  )
  values(
    next_id, next_no, p_kind, p_severity, 'published', p_title, p_body,
    'specific_users', p_org_unit_id, p_operation_id,
    jsonb_build_object('user_ids', jsonb_build_array(p_user_id::text)),
    p_action_url, p_source_key, now(), p_created_by
  )
  on conflict (source_key) do nothing;

  if not found then
    select id into next_id
    from public.notification_messages
    where source_key = p_source_key;
    return next_id;
  end if;

  insert into public.notification_deliveries(message_id, recipient_user_id)
  values(next_id, p_user_id)
  on conflict (message_id, recipient_user_id) do nothing;

  return next_id;
end;
$$;

create or replace function app_private.notify_duty_assignment_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  duty_row public.operation_duties;
  operation_row public.operations;
  volunteer_row public.volunteer_profiles;
  start_at timestamptz;
  start_text text;
  location_text text;
  source text;
begin
  if new.status <> 'assigned'::public.duty_status then
    return new;
  end if;

  if tg_op = 'UPDATE'
     and old.status = new.status
     and old.assigned_at is not distinct from new.assigned_at then
    return new;
  end if;

  select * into duty_row from public.operation_duties where id = new.duty_id;
  select * into operation_row from public.operations where id = duty_row.operation_id;
  select * into volunteer_row from public.volunteer_profiles where id = new.volunteer_id;

  if duty_row.id is null or operation_row.id is null or volunteer_row.user_id is null then
    return new;
  end if;

  select coalesce(duty_row.starts_at, s.starts_at, operation_row.starts_at)
    into start_at
  from public.operation_duties d
  left join public.operation_shifts s on s.id = duty_row.shift_id
  where d.id = duty_row.id;

  start_text := case when start_at is null then 'Time to be confirmed' else to_char(start_at, 'DD Mon YYYY HH24:MI TZ') end;
  location_text := coalesce(nullif(trim(duty_row.location), ''), nullif(trim(operation_row.location), ''), 'Location to be confirmed');
  source := 'duty-assigned:' || new.id::text || ':' || floor(extract(epoch from new.assigned_at))::bigint::text;

  perform app_private.publish_direct_notification_to_user(
    volunteer_row.user_id,
    duty_row.org_unit_id,
    duty_row.operation_id,
    'duty_reminder'::public.notification_kind,
    case duty_row.priority
      when 'urgent'::public.duty_priority then 'critical'::public.notification_severity
      when 'high'::public.duty_priority then 'warning'::public.notification_severity
      else 'info'::public.notification_severity
    end,
    'New duty assigned: ' || duty_row.title,
    operation_row.title || ' · ' || start_text || ' · ' || location_text,
    '/volunteer',
    source,
    new.assigned_by
  );

  return new;
end;
$$;

create or replace function app_private.generate_due_duty_reminders_impl(
  p_horizon_hours integer default 24
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  safe_hours integer := greatest(1, least(coalesce(p_horizon_hours, 24), 168));
  row_data record;
  generated integer := 0;
  source text;
begin
  if actor is null then raise exception 'Authentication required'; end if;
  if not app_private.can_view_command_center(actor) then raise exception 'Command center access required'; end if;

  for row_data in
    select
      da.id as assignment_id,
      da.assigned_by,
      vp.user_id,
      od.id as duty_id,
      od.title as duty_title,
      od.priority,
      od.org_unit_id,
      od.operation_id,
      o.title as operation_title,
      coalesce(od.starts_at, os.starts_at, o.starts_at) as starts_at,
      coalesce(nullif(trim(od.location), ''), nullif(trim(os.location), ''), nullif(trim(o.location), ''), 'Location to be confirmed') as location
    from public.duty_assignments da
    join public.operation_duties od on od.id = da.duty_id and od.is_active
    join public.operations o on o.id = od.operation_id
    join public.volunteer_profiles vp on vp.id = da.volunteer_id and vp.is_active
    left join public.operation_shifts os on os.id = od.shift_id and os.is_active
    where da.status in ('assigned'::public.duty_status, 'accepted'::public.duty_status)
      and coalesce(od.starts_at, os.starts_at, o.starts_at) is not null
      and coalesce(od.starts_at, os.starts_at, o.starts_at) >= now()
      and coalesce(od.starts_at, os.starts_at, o.starts_at) <= now() + make_interval(hours => safe_hours)
      and app_private.can_manage_operation(actor, od.operation_id)
    order by coalesce(od.starts_at, os.starts_at, o.starts_at)
  loop
    source := 'duty-due:' || row_data.assignment_id::text || ':' || floor(extract(epoch from row_data.starts_at))::bigint::text;

    if not exists (select 1 from public.notification_messages m where m.source_key = source) then
      perform app_private.publish_direct_notification_to_user(
        row_data.user_id,
        row_data.org_unit_id,
        row_data.operation_id,
        'duty_reminder'::public.notification_kind,
        case row_data.priority
          when 'urgent'::public.duty_priority then 'critical'::public.notification_severity
          when 'high'::public.duty_priority then 'warning'::public.notification_severity
          else 'warning'::public.notification_severity
        end,
        'Duty reminder: ' || row_data.duty_title,
        row_data.operation_title || ' starts ' || to_char(row_data.starts_at, 'DD Mon YYYY HH24:MI TZ') || ' · ' || row_data.location,
        '/volunteer',
        source,
        actor
      );
      generated := generated + 1;
    end if;
  end loop;

  if generated > 0 then
    insert into public.audit_events(actor_id, action, entity_type, entity_id, org_unit_id, detail)
    values(actor, 'duty_reminders_generated', 'notification_batch', null, null,
      jsonb_build_object('generated_count', generated, 'horizon_hours', safe_hours));
  end if;

  return generated;
end;
$$;

create or replace function app_private.notify_operation_status_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_id uuid := gen_random_uuid();
  next_no text := 'PTI-NOT-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(replace(next_id::text, '-', ''), 1, 8));
  source text;
  recipient_total integer;
begin
  if old.status is not distinct from new.status then return new; end if;
  if new.status = 'draft'::public.operation_status then return new; end if;

  source := 'operation-status:' || new.id::text || ':' || new.status::text || ':' || floor(extract(epoch from now()))::bigint::text;

  insert into public.notification_messages(
    id, notification_no, kind, severity, status, title, body, audience,
    org_unit_id, operation_id, target_spec, action_url, source_key,
    published_at, created_by
  )
  values(
    next_id,
    next_no,
    'operation_update',
    case new.status
      when 'cancelled'::public.operation_status then 'critical'::public.notification_severity
      when 'active'::public.operation_status then 'success'::public.notification_severity
      when 'completed'::public.operation_status then 'success'::public.notification_severity
      else 'info'::public.notification_severity
    end,
    'published',
    'Operation update: ' || new.title,
    'Status changed to ' || upper(replace(new.status::text, '_', ' ')) || '.',
    'operation_participants',
    new.org_unit_id,
    new.id,
    '{}'::jsonb,
    '/volunteer',
    source,
    now(),
    auth.uid()
  )
  on conflict (source_key) do nothing;

  if not found then return new; end if;

  insert into public.notification_deliveries(message_id, recipient_user_id)
  select next_id, recipients.user_id
  from app_private.notification_recipient_ids(
    'operation_participants'::public.notification_audience,
    new.org_unit_id,
    new.id,
    '{}'::jsonb
  ) recipients
  on conflict (message_id, recipient_user_id) do nothing;

  get diagnostics recipient_total = row_count;

  if recipient_total = 0 then
    delete from public.notification_messages where id = next_id;
  end if;

  return new;
end;
$$;

revoke all on function app_private.my_command_center_access_impl() from public, anon, authenticated;
revoke all on function app_private.list_notification_scopes_impl() from public, anon, authenticated;
revoke all on function app_private.list_notification_operations_impl(uuid) from public, anon, authenticated;
revoke all on function app_private.my_notification_unread_count_impl() from public, anon, authenticated;
revoke all on function app_private.list_my_notifications_impl(integer,timestamptz) from public, anon, authenticated;
revoke all on function app_private.mark_my_notification_read_impl(bigint) from public, anon, authenticated;
revoke all on function app_private.mark_all_my_notifications_read_impl() from public, anon, authenticated;
revoke all on function app_private.archive_my_notification_impl(bigint) from public, anon, authenticated;
revoke all on function app_private.list_command_center_messages_impl(uuid,integer) from public, anon, authenticated;
revoke all on function app_private.publish_notification_impl(uuid,public.notification_kind,public.notification_severity,text,text,public.notification_audience,uuid,text,timestamptz,jsonb) from public, anon, authenticated;
revoke all on function app_private.cancel_notification_impl(uuid) from public, anon, authenticated;
revoke all on function app_private.publish_direct_notification_to_user(uuid,uuid,uuid,public.notification_kind,public.notification_severity,text,text,text,text,uuid) from public, anon, authenticated;
revoke all on function app_private.generate_due_duty_reminders_impl(integer) from public, anon, authenticated;
revoke all on function app_private.notify_duty_assignment_trigger() from public, anon, authenticated;
revoke all on function app_private.notify_operation_status_trigger() from public, anon, authenticated;

-- SECURITY INVOKER wrappers need EXECUTE on their private implementation, while
-- the app_private schema remains outside the exposed PostgREST API schema.
grant execute on function app_private.my_command_center_access_impl() to authenticated;
grant execute on function app_private.list_notification_scopes_impl() to authenticated;
grant execute on function app_private.list_notification_operations_impl(uuid) to authenticated;
grant execute on function app_private.my_notification_unread_count_impl() to authenticated;
grant execute on function app_private.list_my_notifications_impl(integer,timestamptz) to authenticated;
grant execute on function app_private.mark_my_notification_read_impl(bigint) to authenticated;
grant execute on function app_private.mark_all_my_notifications_read_impl() to authenticated;
grant execute on function app_private.archive_my_notification_impl(bigint) to authenticated;
grant execute on function app_private.list_command_center_messages_impl(uuid,integer) to authenticated;
grant execute on function app_private.publish_notification_impl(uuid,public.notification_kind,public.notification_severity,text,text,public.notification_audience,uuid,text,timestamptz,jsonb) to authenticated;
grant execute on function app_private.cancel_notification_impl(uuid) to authenticated;
grant execute on function app_private.generate_due_duty_reminders_impl(integer) to authenticated;

-- Trigger-only helpers stay non-callable from client roles.

-- -----------------------------------------------------------------------------
-- Public RPC wrappers — SECURITY INVOKER by design
-- -----------------------------------------------------------------------------

create or replace function public.my_command_center_access()
returns table(
  can_view boolean,
  can_manage boolean,
  default_org_unit_id uuid,
  default_org_unit_name text,
  default_org_unit_level public.organization_level
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.my_command_center_access_impl();
$$;

create or replace function public.list_notification_scopes()
returns table(
  id uuid,
  parent_id uuid,
  level public.organization_level,
  name text,
  code text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.list_notification_scopes_impl();
$$;

create or replace function public.list_notification_operations(
  p_org_unit_id uuid default null
)
returns table(
  id uuid,
  org_unit_id uuid,
  org_unit_name text,
  title text,
  status public.operation_status,
  starts_at timestamptz,
  ends_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.list_notification_operations_impl(p_org_unit_id);
$$;

create or replace function public.my_notification_unread_count()
returns bigint
language sql
stable
security invoker
set search_path = ''
as $$
  select app_private.my_notification_unread_count_impl();
$$;

create or replace function public.list_my_notifications(
  p_limit integer default 50,
  p_before timestamptz default null
)
returns table(
  delivery_id bigint,
  message_id uuid,
  notification_no text,
  kind public.notification_kind,
  severity public.notification_severity,
  title text,
  body text,
  action_url text,
  operation_id uuid,
  org_unit_id uuid,
  org_unit_name text,
  published_at timestamptz,
  expires_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  archived_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.list_my_notifications_impl(p_limit, p_before);
$$;

create or replace function public.mark_my_notification_read(p_delivery_id bigint)
returns void
language sql
security invoker
set search_path = ''
as $$
  select app_private.mark_my_notification_read_impl(p_delivery_id);
$$;

create or replace function public.mark_all_my_notifications_read()
returns integer
language sql
security invoker
set search_path = ''
as $$
  select app_private.mark_all_my_notifications_read_impl();
$$;

create or replace function public.archive_my_notification(p_delivery_id bigint)
returns void
language sql
security invoker
set search_path = ''
as $$
  select app_private.archive_my_notification_impl(p_delivery_id);
$$;

create or replace function public.list_command_center_messages(
  p_org_unit_id uuid default null,
  p_limit integer default 50
)
returns table(
  id uuid,
  notification_no text,
  kind public.notification_kind,
  severity public.notification_severity,
  status public.notification_status,
  title text,
  body text,
  audience public.notification_audience,
  org_unit_id uuid,
  org_unit_name text,
  operation_id uuid,
  operation_title text,
  action_url text,
  published_at timestamptz,
  expires_at timestamptz,
  created_by uuid,
  recipient_count bigint,
  read_count bigint,
  unread_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select * from app_private.list_command_center_messages_impl(p_org_unit_id, p_limit);
$$;

create or replace function public.publish_notification(
  p_org_unit_id uuid,
  p_kind public.notification_kind,
  p_severity public.notification_severity,
  p_title text,
  p_body text,
  p_audience public.notification_audience,
  p_operation_id uuid default null,
  p_action_url text default null,
  p_expires_at timestamptz default null,
  p_target_spec jsonb default '{}'::jsonb
)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select app_private.publish_notification_impl(
    p_org_unit_id,
    p_kind,
    p_severity,
    p_title,
    p_body,
    p_audience,
    p_operation_id,
    p_action_url,
    p_expires_at,
    p_target_spec
  );
$$;

create or replace function public.cancel_notification(p_message_id uuid)
returns void
language sql
security invoker
set search_path = ''
as $$
  select app_private.cancel_notification_impl(p_message_id);
$$;

create or replace function public.generate_due_duty_reminders(p_horizon_hours integer default 24)
returns integer
language sql
security invoker
set search_path = ''
as $$
  select app_private.generate_due_duty_reminders_impl(p_horizon_hours);
$$;

revoke all on function public.my_command_center_access() from public, anon, authenticated;
revoke all on function public.list_notification_scopes() from public, anon, authenticated;
revoke all on function public.list_notification_operations(uuid) from public, anon, authenticated;
revoke all on function public.my_notification_unread_count() from public, anon, authenticated;
revoke all on function public.list_my_notifications(integer,timestamptz) from public, anon, authenticated;
revoke all on function public.mark_my_notification_read(bigint) from public, anon, authenticated;
revoke all on function public.mark_all_my_notifications_read() from public, anon, authenticated;
revoke all on function public.archive_my_notification(bigint) from public, anon, authenticated;
revoke all on function public.list_command_center_messages(uuid,integer) from public, anon, authenticated;
revoke all on function public.publish_notification(uuid,public.notification_kind,public.notification_severity,text,text,public.notification_audience,uuid,text,timestamptz,jsonb) from public, anon, authenticated;
revoke all on function public.cancel_notification(uuid) from public, anon, authenticated;
revoke all on function public.generate_due_duty_reminders(integer) from public, anon, authenticated;

grant execute on function public.my_command_center_access() to authenticated;
grant execute on function public.list_notification_scopes() to authenticated;
grant execute on function public.list_notification_operations(uuid) to authenticated;
grant execute on function public.my_notification_unread_count() to authenticated;
grant execute on function public.list_my_notifications(integer,timestamptz) to authenticated;
grant execute on function public.mark_my_notification_read(bigint) to authenticated;
grant execute on function public.mark_all_my_notifications_read() to authenticated;
grant execute on function public.archive_my_notification(bigint) to authenticated;
grant execute on function public.list_command_center_messages(uuid,integer) to authenticated;
grant execute on function public.publish_notification(uuid,public.notification_kind,public.notification_severity,text,text,public.notification_audience,uuid,text,timestamptz,jsonb) to authenticated;
grant execute on function public.cancel_notification(uuid) to authenticated;
grant execute on function public.generate_due_duty_reminders(integer) to authenticated;

-- -----------------------------------------------------------------------------
-- RLS + direct-table lockdown
-- -----------------------------------------------------------------------------

alter table public.notification_messages enable row level security;
alter table public.notification_deliveries enable row level security;

create policy notification_messages_select_command_center
on public.notification_messages
for select
to authenticated
using (
  app_private.can_view_command_center((select auth.uid()))
  and (
    app_private.can_manage_notifications((select auth.uid()), org_unit_id)
    or (operation_id is not null and app_private.can_manage_operation((select auth.uid()), operation_id))
    or app_private.can_access_org_unit((select auth.uid()), org_unit_id)
  )
);

create policy notification_deliveries_select_own
on public.notification_deliveries
for select
to authenticated
using (recipient_user_id = (select auth.uid()));

revoke all on public.notification_messages from public, anon, authenticated;
revoke all on public.notification_deliveries from public, anon, authenticated;

-- Deliberately expose no direct table privileges. All client access goes through
-- the hardened RPC boundary above.

-- -----------------------------------------------------------------------------
-- Automatic operational notifications
-- -----------------------------------------------------------------------------

drop trigger if exists duty_assignments_notify_assignment on public.duty_assignments;
create trigger duty_assignments_notify_assignment
after insert or update of status, assigned_at on public.duty_assignments
for each row execute function app_private.notify_duty_assignment_trigger();

drop trigger if exists operations_notify_status_change on public.operations;
create trigger operations_notify_status_change
after update of status on public.operations
for each row execute function app_private.notify_operation_status_trigger();

commit;
