/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardRouteImport } from './routes/card'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyMemberNoRouteImport } from './routes/verify/$memberNo'
import { Route as OperationsWorkbenchRouteImport } from './routes/operations/workbench'
import { Route as OperationsVolunteersRouteImport } from './routes/operations/volunteers'
import { Route as OperationsAttendanceRouteImport } from './routes/operations/attendance'
import { Route as FinanceWorkbenchRouteImport } from './routes/finance/workbench'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminOrganizationRouteImport } from './routes/admin/organization'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as FinanceReceiptReceiptNoRouteImport } from './routes/finance/receipt/$receiptNo'
import { Route as AttendanceCheckInTokenRouteImport } from './routes/attendance/check-in/$token'
import { Route as AdminMembersIdRouteImport } from './routes/admin/members/$id'
import { Route as AdminMembersIdCardRouteImport } from './routes/admin/members/$id/card'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMemberNoRoute = VerifyMemberNoRouteImport.update({
  id: '/verify/$memberNo',
  path: '/verify/$memberNo',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsWorkbenchRoute = OperationsWorkbenchRouteImport.update({
  id: '/operations/workbench',
  path: '/operations/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsVolunteersRoute = OperationsVolunteersRouteImport.update({
  id: '/operations/volunteers',
  path: '/operations/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsAttendanceRoute = OperationsAttendanceRouteImport.update({
  id: '/operations/attendance',
  path: '/operations/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceWorkbenchRoute = FinanceWorkbenchRouteImport.update({
  id: '/finance/workbench',
  path: '/finance/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const FinanceReceiptReceiptNoRoute = FinanceReceiptReceiptNoRouteImport.update({
  id: '/finance/receipt/$receiptNo',
  path: '/finance/receipt/$receiptNo',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceCheckInTokenRoute = AttendanceCheckInTokenRouteImport.update({
  id: '/attendance/check-in/$token',
  path: '/attendance/check-in/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersIdCardRoute = AdminMembersIdCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AdminMembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/finance/workbench': typeof FinanceWorkbenchRoute
  '/operations/attendance': typeof OperationsAttendanceRoute
  '/operations/volunteers': typeof OperationsVolunteersRoute
  '/operations/workbench': typeof OperationsWorkbenchRoute
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/attendance/check-in/$token': typeof AttendanceCheckInTokenRoute
  '/finance/receipt/$receiptNo': typeof FinanceReceiptReceiptNoRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/finance/workbench': typeof FinanceWorkbenchRoute
  '/operations/attendance': typeof OperationsAttendanceRoute
  '/operations/volunteers': typeof OperationsVolunteersRoute
  '/operations/workbench': typeof OperationsWorkbenchRoute
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/attendance/check-in/$token': typeof AttendanceCheckInTokenRoute
  '/finance/receipt/$receiptNo': typeof FinanceReceiptReceiptNoRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/card': typeof CardRoute
  '/dashboard': typeof DashboardRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/finance/workbench': typeof FinanceWorkbenchRoute
  '/operations/attendance': typeof OperationsAttendanceRoute
  '/operations/volunteers': typeof OperationsVolunteersRoute
  '/operations/workbench': typeof OperationsWorkbenchRoute
  '/verify/$memberNo': typeof VerifyMemberNoRoute
  '/admin/members/$id': typeof AdminMembersIdRouteWithChildren
  '/attendance/check-in/$token': typeof AttendanceCheckInTokenRoute
  '/finance/receipt/$receiptNo': typeof FinanceReceiptReceiptNoRoute
  '/admin/members/$id/card': typeof AdminMembersIdCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/leadership'
    | '/login'
    | '/register'
    | '/signup'
    | '/volunteer'
    | '/admin/audit'
    | '/admin/organization'
    | '/admin/roles'
    | '/finance/workbench'
    | '/operations/attendance'
    | '/operations/volunteers'
    | '/operations/workbench'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/attendance/check-in/$token'
    | '/finance/receipt/$receiptNo'
    | '/admin/members/$id/card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/leadership'
    | '/login'
    | '/register'
    | '/signup'
    | '/volunteer'
    | '/admin/audit'
    | '/admin/organization'
    | '/admin/roles'
    | '/finance/workbench'
    | '/operations/attendance'
    | '/operations/volunteers'
    | '/operations/workbench'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/attendance/check-in/$token'
    | '/finance/receipt/$receiptNo'
    | '/admin/members/$id/card'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/card'
    | '/dashboard'
    | '/leadership'
    | '/login'
    | '/register'
    | '/signup'
    | '/volunteer'
    | '/admin/audit'
    | '/admin/organization'
    | '/admin/roles'
    | '/finance/workbench'
    | '/operations/attendance'
    | '/operations/volunteers'
    | '/operations/workbench'
    | '/verify/$memberNo'
    | '/admin/members/$id'
    | '/attendance/check-in/$token'
    | '/finance/receipt/$receiptNo'
    | '/admin/members/$id/card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CardRoute: typeof CardRoute
  DashboardRoute: typeof DashboardRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  VolunteerRoute: typeof VolunteerRoute
  FinanceWorkbenchRoute: typeof FinanceWorkbenchRoute
  OperationsAttendanceRoute: typeof OperationsAttendanceRoute
  OperationsVolunteersRoute: typeof OperationsVolunteersRoute
  OperationsWorkbenchRoute: typeof OperationsWorkbenchRoute
  VerifyMemberNoRoute: typeof VerifyMemberNoRoute
  AttendanceCheckInTokenRoute: typeof AttendanceCheckInTokenRoute
  FinanceReceiptReceiptNoRoute: typeof FinanceReceiptReceiptNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$memberNo': {
      id: '/verify/$memberNo'
      path: '/verify/$memberNo'
      fullPath: '/verify/$memberNo'
      preLoaderRoute: typeof VerifyMemberNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/workbench': {
      id: '/operations/workbench'
      path: '/operations/workbench'
      fullPath: '/operations/workbench'
      preLoaderRoute: typeof OperationsWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/volunteers': {
      id: '/operations/volunteers'
      path: '/operations/volunteers'
      fullPath: '/operations/volunteers'
      preLoaderRoute: typeof OperationsVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/attendance': {
      id: '/operations/attendance'
      path: '/operations/attendance'
      fullPath: '/operations/attendance'
      preLoaderRoute: typeof OperationsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/workbench': {
      id: '/finance/workbench'
      path: '/finance/workbench'
      fullPath: '/finance/workbench'
      preLoaderRoute: typeof FinanceWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/finance/receipt/$receiptNo': {
      id: '/finance/receipt/$receiptNo'
      path: '/finance/receipt/$receiptNo'
      fullPath: '/finance/receipt/$receiptNo'
      preLoaderRoute: typeof FinanceReceiptReceiptNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/check-in/$token': {
      id: '/attendance/check-in/$token'
      path: '/attendance/check-in/$token'
      fullPath: '/attendance/check-in/$token'
      preLoaderRoute: typeof AttendanceCheckInTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members/$id/card': {
      id: '/admin/members/$id/card'
      path: '/card'
      fullPath: '/admin/members/$id/card'
      preLoaderRoute: typeof AdminMembersIdCardRouteImport
      parentRoute: typeof AdminMembersIdRoute
    }
  }
}

interface AdminMembersIdRouteChildren {
  AdminMembersIdCardRoute: typeof AdminMembersIdCardRoute
}

const AdminMembersIdRouteChildren: AdminMembersIdRouteChildren = {
  AdminMembersIdCardRoute: AdminMembersIdCardRoute,
}

const AdminMembersIdRouteWithChildren = AdminMembersIdRoute._addFileChildren(
  AdminMembersIdRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminMembersIdRoute: typeof AdminMembersIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminMembersIdRoute: AdminMembersIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CardRoute: CardRoute,
  DashboardRoute: DashboardRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  VolunteerRoute: VolunteerRoute,
  FinanceWorkbenchRoute: FinanceWorkbenchRoute,
  OperationsAttendanceRoute: OperationsAttendanceRoute,
  OperationsVolunteersRoute: OperationsVolunteersRoute,
  OperationsWorkbenchRoute: OperationsWorkbenchRoute,
  VerifyMemberNoRoute: VerifyMemberNoRoute,
  AttendanceCheckInTokenRoute: AttendanceCheckInTokenRoute,
  FinanceReceiptReceiptNoRoute: FinanceReceiptReceiptNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
